### ISSUE TITLE
About the LengthIoU loss

### ISSUE THREAD

**Issue by gintamatyy** [ljn114514/PolarPose#1]
Congratulations on the TIP publication, and thanks for sharing your code. I am interested in this method, especially the LengthIoU loss in your paper. But I did not find the code for it. Could you show me the implementation of this loss or tell me the path of the code if I missed it?

**Comment by rika1024** [comment]
You can find it at line 170-175 in models/kpt_head.py

**Comment by gintamatyy** [comment]
Thank you for your reply! While I found PolarIoU loss rather than LengthIoU loss here. Did the gt_lens* cos(δθ) finish before kpt_head?

**Comment by rika1024** [comment]
The line 170-175 in models/kpt_head.py corresponding to equal 10 in the paper. If you mean equal 11, you can find it at line 367-374.(replace line 361-365)

**Comment by gintamatyy** [comment]
Got it!    Thanks for your help!
